### ISSUE TITLE
Add also mac filename to be sanitized

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-sanitize-filename#1]
As mac has his own filename system encoding format, they are not sanitized. So we must :
- [ ] Find out what is the list of mac encoded common special chars
- [ ] Apply them on the same sanitized hook

**Comment by MaximeCulea** [comment]
Maybe have a look here : https://core.trac.wordpress.org/ticket/24661
Thx @petitphp

**Comment by Julianoe** [comment]
Just so you know, this Wordpress issue has been resolved for the latest version of Wordpress
see commit https://core.trac.wordpress.org/changeset/53754
