### ISSUE TITLE
Undefined offset: 0 on line 41

### ISSUE THREAD

**Issue by css31** [BeAPI/bea-sanitize-filename#6]
Notice: Undefined offset: 0 in /home/sites/dev.example.com/wp-content/mu-plugins/bea-sanitize-filename.php on line 41

**Comment by MaximeCulea** [comment]
Just a notice, but will still change the preg_match for extension with the [pathinfo](http://php.net/manual/fr/function.pathinfo.php) method.

**Comment by herewithme** [comment]
Fixed on:
https://github.com/BeAPI/bea-sanitize-filename/commit/853e491d9153f6ecd225509ee21681994aca32e3
